apiVersion: v1
kind: Secret
metadata:
  name: user-service-db
  namespace: angular-micro
type: Opaque
stringData:
  connection-string: "Host=postgres;Port=5432;Database=userservicedb;Username=postgres;Password=postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: product-service-db
  namespace: angular-micro
type: Opaque
stringData:
  connection-string: "Host=postgres;Port=5432;Database=productservicedb;Username=postgres;Password=postgres"
