apiVersion: batch/v1
kind: Job
metadata:
  name: product-migrations
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: your-product-service-image:latest
        command: ["dotnet", "ProductService.dll"]
      restartPolicy: OnFailure
  