apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micro-ingress
  namespace: angular-micro
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: local.micro
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: angular-client
                port:
                  number: 80
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 5000
