apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: angular-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ghcr.io/hitsshaa/microservicesapp/product-service:latest
          ports:
            - containerPort: 5200
          readinessProbe:
            httpGet:
              path: /health
              port: 5200
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5200
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5200
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: angular-micro
spec:
  selector:
    app: product-service
  ports:
    - port: 5200
      targetPort: 5200
      protocol: TCP
      name: http
  type: ClusterIP
