apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: angular-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      initContainers:
      - name: wait-for-sql
        image: mcr.microsoft.com/mssql-tools
        command:
          - /bin/sh
          - -c
          - |
            echo "Waiting for SQL Server..."
            until /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'Hitesh12@' -Q "SELECT 1" &>/dev/null
            do
              echo -n "."
              sleep 5
            done
      containers:
      - name: product-service
        image: ghcr.io/hitsshaa/microservicesapp/product-service:latest
        ports:
        - containerPort: 5200
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:5200"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: product-service-secret
              key: connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: angular-micro
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
  - port: 5200
    targetPort: 5200
