apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: angular-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/your-org/user-service:latest
          ports:
            - containerPort: 5100
          readinessProbe:
            httpGet:
              path: /health
              port: 5100
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5100
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5100
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: angular-micro
spec:
  selector:
    app: user-service
  ports:
    - port: 5100
      targetPort: 5100
      protocol: TCP
      name: http
  type: ClusterIP
