apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: angular-micro-eks
  region: us-east-1
  version: "1.30"

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single

iam:
  withOIDC: true

managedNodeGroups:
  - name: ng-default
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: true
    volumeSize: 30
    volumeType: gp3
    labels:
      role: worker
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
        cloudWatch: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]
